# Generated by Django 5.0.4 on 2024-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centredesanté',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('DateNaissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Praticien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('DateNaissance', models.DateField()),
                ('spécialité', models.CharField(max_length=300)),
            ],
        ),
    ]
